name: follow
description: Follow App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_color_utilities:
  dynamic_color:
  font_awesome_flutter:
  url_launcher:
  http:
  webview_flutter:
  receive_sharing_intent:
  connectivity_plus:
  fluttertoast:
  sqflite:
  path:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter-icon:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/